# Generated by Django 4.2.3 on 2023-08-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_taskformmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskformmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
