# Generated by Django 4.2.3 on 2023-09-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='images',
            field=models.ImageField(blank=True, upload_to='photos/chobi'),
        ),
    ]
