# Generated by Django 4.2.3 on 2023-09-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='avg',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='numrating',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
